QuantConnect/Lean.Brokerages.TradeStation

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageAdditionalTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageFactoryTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/Api/TokenRefreshHandler.cs
QuantConnect.TradeStationBrokerage/Api/TradeStationApiClient.cs
QuantConnect.TradeStationBrokerage/Models/Enums/TradeStationOptionType.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerageFactory.cs

- Refactored the BrokerageFactory initialization process.
- Refactored constructors in the TradeStation class.
- Updated tests to support the new constructors.
- Fixed the GetLeanSymbol method in the HandleTSMessage function.
- Added a new property NA in the TSOptionType enum.
- Adjusted tests to handle flexible price scenarios.
N/a
- **Refactoring the BrokerageFactory initialization and TradeStation constructors**: This enhances the clarity and efficiency of the code.
- **Updating tests**: This ensures that the new constructors are properly tested and validated.
- **Fixing the GetLeanSymbol method**: This resolves issues related to symbol handling in TradeStation messages.
- **Adding a new option type in TSOptionType**: This provides additional functionality and flexibility for handling …

Refactor tests and factory initialization

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/Api/TradeStationApiClient.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationPosition.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs

1. **Refactor: Cancellation Token in Stream Orders Event**
- Removed the `cancel order` event in `CancelOrder()` method.
- Updated `handleBrokerEvent` to return an event indicating that the order was cancelled.
2. **Refactor: Test Parameters for Equity and Option**
- Consolidated test parameters for Equity and Option into a single collection.
- Implemented dynamic retrieval of high and low limit prices during each test run to enhance flexibility and accuracy.
3. **Fix: Round Price for Option Contracts**
- Fixed rounding issues for prices of option contracts to ensure accuracy and consistency. `SecurityType.Option` uses some restriction of price like `Price = 18.12000000 not rounded to a valid price increment [ 0.05 ]`.
N/A
- The refactoring of the cancellation token in stream orders event …

Fix: CI/CD

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageAdditionalTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageDataQueueHandlerTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageSymbolMapperTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/Api/TradeStationApiClient.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationBalance.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationOrderResponse.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationPlaceOrderResponse.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationPosition.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationQuoteSnapshot.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.DataQueueHandler.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.DataQueueUniverseProvider.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerageFactory.cs
QuantConnect.TradeStationBrokerage/TradeStationSymbolMapper.cs

This pull request implements a general data queue handler with an aggregator that processes data updates for various resolutions, including tick, second, hour, and daily. The handler is designed to manage updates for both quote and trade bar events, catering to different security types such as Equity, Equity Option, and Future.
N/A
The primary motivation behind this implementation is to enhance the system's ability to handle real-time and historical data streams efficiently. By supporting multiple resolutions and security types, this data queue handler aims to provide a more versatile and robust solution for processing market data. This improvement will facilitate better data management, enabling more accurate and timely insights for various trading strategies.
N/A
The new data queue …

Feature: Data Queue Handler

---

QuantConnect.TradeStationBrokerage/QuantConnect.TradeStationBrokerage.csproj

Fix: Project ref on QC

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/Models/Interfaces/ITradeStationError.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationAccount.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationBalance.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationOptionExpiration.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationOptionStrike.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationOrderResponse.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationPlaceOrderResponse.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationPosition.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationQuoteSnapshot.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs

Minor improvements

---

QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs

- Minor improvements for order event handling

Minor improvements for order event handling

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageAdditionalTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageHistoryProviderTests.cs
QuantConnect.TradeStationBrokerage/Api/TradeStationApiClient.cs
QuantConnect.TradeStationBrokerage/Models/Enums/TradeStationUnitTimeIntervalType.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationBars.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.HistoryProvider.cs
QuantConnect.TradeStationBrokerage/TradeStationExtensions.cs

This pull request implements a history provider for security types: Equity, Equity Option, and Future. The provider supports multiple resolutions, including Minute, Hour, and Daily.
N/A
The purpose of this implementation is to enhance our system by providing comprehensive historical data support for various security types and resolutions. This will allow for more detailed and accurate analysis and operations on the data.
N/A
- Created specific tests with different test cases for each security type (Equity, Equity Option, Future) across all supported resolutions (Minute, Hour, Daily).
- Tested the provider with both valid and invalid parameters to ensure robustness and error handling.

Feature: history provider

---

QuantConnect.TradeStationBrokerage/TradeStationBrokerage.HistoryProvider.cs

Fix missed variable in history request.
N/A
N/A

Fix: wrong variable in history request

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs

Feat: accumulate filled quantity amount

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.HistoryProvider.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs
QuantConnect.TradeStationBrokerage/TradeStationExtensions.cs

This pull request introduces several enhancements and bug fixes to improve the functionality and user experience of our application:
- **feat: Validate Account type before PlaceOrder**
- Added validation to ensure the account type is correct before placing an order.
- **feat: User-friendly error message in GetHistory**
- Implemented a more descriptive error message when the Canonical symbol cannot return historical data.
- **fix: Bug in CrossZero order for Future symbols**
- Corrected the direction used for CrossZero orders in Future symbols.
- **Account Validation**: Ensuring the account type is valid before placing an order is crucial to prevent errors and improve the reliability of the transaction process.
- **User-Friendly Error Messages**: Providing clear and descriptive error …

Feature && Fix: small improvements and fix of TradeAction

---

QuantConnect.TradeStationBrokerage/Models/AccountTypeEnumConverter.cs
QuantConnect.TradeStationBrokerage/Models/Enums/TradeStationAccountType.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationAccount.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationBalance.cs

- Handle unknown account types, we've seen undocumented account types, like forex being returned by the API

Handle unknown account types

---

TradeStation.json

This Pull Request updates the configuration specification for the `Lean.Brokerages.TradeStation` module. The changes aim to enhance the user experience by making the configuration process more intuitive and streamlined.
N/A
The current configuration setup for `Lean.Brokerages.TradeStation` has been found to be somewhat cumbersome and not very user-friendly. This update addresses these issues by:
- Simplifying configuration options
- Implementing default values for common settings to reduce setup time
N/A
N/A

update: TS config file

---

QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs

Missed calculation of the filled quantity of combo orders which were not included in the last TradeStation response.
- https://github.com/QuantConnect/Lean.Brokerages.TradeStation/pull/25
N/A
N/A

Fix: calculation of not filled Combo Orders 

---

QuantConnect.TradeStationBrokerage/Models/Enums/TradeStationDuration.cs

- #29 
N/a
I have created all available Duration in TradeStation with using UX.
Call `GetOpenOrders()` in Brokerage

Fix: new duration in `enum TradeStationDuration`

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageAdditionalTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageFactoryTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage.Tests/config.json
QuantConnect.TradeStationBrokerage/Api/TradeStationApiClient.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.DataQueueHandler.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerageFactory.cs

Add a new configuration parameter "trade-station-account-id" to enable users to switch between different **TradeStation** accounts.
- https://github.com/QuantConnect/lean-cli/pull/500
N/A
Add a new configuration parameter "trade-station-account-id" that allows users to select between different TradeStation accounts or subaccounts, which may be associated with various securities types and balances. This feature enables seamless switching between them.
N/A
- Run a specific test in the TradeStationTest project using different account ID parameters.
- use `lean-cli` and new nuget package.

Feature: new config `account-id`

---

README.md

Add additional support Order Types.
N/a
Develop a more useful description of the repository.
N/a
N/a

fix: support OrderTypes in Readme

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageAdditionalTests.cs
QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/Api/TradeStationApiClient.cs
QuantConnect.TradeStationBrokerage/Models/Enums/PlaceOrderDuration.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationPlaceOrderRequest.cs
QuantConnect.TradeStationBrokerage/TradeStationExtensions.cs

The API support different presentation of TimeInForce:
- POST `PlaceOrder(...)` use TimeInForce:
- Day Plus => `DYP`
- Good till canceled plus => `GCP`
- Good through date plus => `GDP`
- GET `GetOpenOrders(...)` return TimeInForce:
-  Day Plus => `DAY+`
- Good till canceled plus => `GTC+`
- Good through date plus => `GTD+`
#34

Feature: support `OutsideRegularTradingHours`

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/Api/TradeStationApiClient.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationPlaceOrderRequest.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs

Support post-only orders. Enabled by setting order advanced options BookOnly and AddLiquidity to true
Depends on  https://github.com/QuantConnect/Lean/pull/8787
Closes #43

Support post-only orders

---

QuantConnect.TradeStationBrokerage.Tests/TradeStationBrokerageTests.cs
QuantConnect.TradeStationBrokerage/Api/TradeStationApiClient.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationOrderResponse.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationPlaceOrderRequest.cs
QuantConnect.TradeStationBrokerage/Models/TradeStationReplaceOrderRequest.cs
QuantConnect.TradeStationBrokerage/TradeStationBrokerage.cs
QuantConnect.TradeStationBrokerage/TradeStationExtensions.cs
TradeStation.json

Support trailing stop orders
Depends https://github.com/QuantConnect/Lean/pull/8780
Closes #46

Support trailing stop orders

---

TradeStation.json

adds qc landing page url
